### PR TITLE
List projects by folder

### PR DESCRIPTION
**Pull request by kragt**
Implemented the command to list projects by folder. It will list all projects in a given folder or any subfolders. 

This looks in any subfolders from the supplied folder as just listing the project(s) in a specific given folder didn't seem overly useful.

### CODE REVIEW

**Comment by kragt** [comment]
Listing results relative to the search folder for more legible output.

**Comment by Krzysztof-Cieslak** [comment]
Tests, please  ;-)

**Comment by kragt** [comment]
Yes, about that, since I was looking for it for writing some of the other tests. Can I test console output with Expecto? I can't find anything about it, and all the list commands just prints the results.

**Comment by kragt** [comment]
Added test.

**Pull request merged**
